name: mirror_on_push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: wearerequired/git-mirror-action@master
    - env: 
        SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
    - with:
        source-repo: 'git@github.com/morrieinmaas/testclonesource.git'
        destination-repo: 'git@gitlab.encompasshost.com/moritz.schlichting/testclonedestination.git'
